language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
os:
  - linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - librsvg2-2
    - libcairo2
    - libglib2.0-0
    - gobject-introspection
