language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
os:
  - linux
install:
  - cpanm --verbose --no-interactive ExtUtils::PkgConfig
  - cpanm --verbose --installdeps --no-interactive --notest .
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - librsvg2-2
    - gobject-introspection
    - libgirepository1.0-dev
